"""Inline the pixel fonts into public/play.html, subset to the characters the player can see.

The player bundle is an allowlist of eight files (tests/progressive-disclosure.test.mjs), so the
fonts cannot ship as files: they are base64 data URIs inside play.html, between the
`pixel-fonts:begin` / `pixel-fonts:end` markers. Subsetting keeps that under ~100 KB instead of
the 600 KB full CJK font.

Run after changing any player-visible copy:

    python3 -m pip install fonttools brotli
    python3 scripts/pixel-font/subset.py

It rewrites the block in play.html and scripts/pixel-font/charset.txt; tests/pixel-font.test.mjs
fails when the sources contain a character that charset.txt does not account for.

Fusion Pixel carries the Reserved Font Name "Fusion Pixel" (OFL 1.1), and a subset is a modified
version, so the subset is renamed "Glyph Pixel". Silkscreen has no reserved name.
"""
import base64
import hashlib
import io
import re
from pathlib import Path

from fontTools import subset
from fontTools.ttLib import TTFont

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent
PLAY = ROOT / 'public/play.html'
SOURCES = ['public/glyph-engine-v3.js', 'public/glyph-game-v3.js', 'public/player-privacy-v3.js']
BEGIN, END = '/* pixel-fonts:begin', '/* pixel-fonts:end */'


def source_chars():
    html = PLAY.read_text(encoding='utf8')
    if BEGIN in html:
        html = html[:html.index(BEGIN)] + html[html.index(END) + len(END):]
    text = html + ''.join((ROOT / p).read_text(encoding='utf8') for p in SOURCES)
    chars = {c for c in text if ord(c) > 0x7e and not c.isspace()}
    chars |= {chr(c) for c in range(0x20, 0x7f)}
    return chars


def build(src, chars, family):
    font = TTFont(src)
    cmap = font.getBestCmap()
    covered = sorted(c for c in chars if ord(c) in cmap)
    opts = subset.Options()
    opts.flavor = 'woff2'
    opts.layout_features = ['*']
    opts.name_IDs = ['*']
    sub = subset.Subsetter(opts)
    sub.populate(unicodes=[ord(c) for c in covered])
    sub.subset(font)
    for rec in font['name'].names:
        if rec.nameID in (1, 3, 4, 6, 16):
            rec.string = family.replace(' ', '') if rec.nameID == 6 else family
    buf = io.BytesIO()
    font.flavor = 'woff2'
    font.save(buf)
    return buf.getvalue(), set(covered)


def main():
    chars = source_chars()
    cjk, cjk_cov = build(HERE / 'FusionPixel-12px-SC.woff2', chars, 'Glyph Pixel')
    latin, _ = build(HERE / 'Silkscreen-400.woff2', {chr(c) for c in range(0x20, 0x7f)}, 'Silkscreen')
    b64 = lambda data: base64.b64encode(data).decode('ascii')
    block = (
        f"{BEGIN} generated by scripts/pixel-font/subset.py — do not edit */\n"
        f"@font-face{{font-family:\"Glyph Pixel\";src:url(data:font/woff2;base64,{b64(cjk)}) format(\"woff2\");font-display:block}}\n"
        f"@font-face{{font-family:\"Silkscreen\";src:url(data:font/woff2;base64,{b64(latin)}) format(\"woff2\");font-display:block}}\n"
        f"{END}"
    )
    html = PLAY.read_text(encoding='utf8')
    if BEGIN in html:
        html = html[:html.index(BEGIN)] + block + html[html.index(END) + len(END):]
    else:
        html = html.replace('<style>\n', '<style>\n' + block + '\n', 1)
    PLAY.write_text(html, encoding='utf8')
    digest = hashlib.sha256(block.encode('utf8')).hexdigest()
    fallback = sorted(chars - cjk_cov)
    (HERE / 'charset.txt').write_text(
        f'block-sha256 {digest}\n'
        f'covered {"".join(sorted(cjk_cov))}\n'
        f'fallback {"".join(fallback)}\n', encoding='utf8')
    print(f'Glyph Pixel {len(cjk)} B · {len(cjk_cov)} glyphs · Silkscreen {len(latin)} B · fallback {"".join(fallback)!r}')


if __name__ == '__main__':
    main()
